// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Analysis struct {
	ID               int64        `json:"id"`
	ArticleID        int64        `json:"article_id"`
	Summary          string       `json:"summary"`
	Sentiment        string       `json:"sentiment"`
	Impact           string       `json:"impact"`
	Tickers          string       `json:"tickers"`
	ReferenceLinks   string       `json:"reference_links"`
	AnalyzedAt       sql.NullTime `json:"analyzed_at"`
	ReliabilityScore int64        `json:"reliability_score"`
}

type Article struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	Link        string       `json:"link"`
	Content     string       `json:"content"`
	Source      string       `json:"source"`
	PublishedAt time.Time    `json:"published_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
