// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAnalysis = `-- name: CreateAnalysis :one
INSERT INTO analyses (article_id, summary, sentiment, impact, tickers, reference_links, reliability_score)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, article_id, summary, sentiment, impact, tickers, reference_links, analyzed_at, reliability_score
`

type CreateAnalysisParams struct {
	ArticleID        int64  `json:"article_id"`
	Summary          string `json:"summary"`
	Sentiment        string `json:"sentiment"`
	Impact           string `json:"impact"`
	Tickers          string `json:"tickers"`
	ReferenceLinks   string `json:"reference_links"`
	ReliabilityScore int64  `json:"reliability_score"`
}

func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error) {
	row := q.db.QueryRowContext(ctx, createAnalysis,
		arg.ArticleID,
		arg.Summary,
		arg.Sentiment,
		arg.Impact,
		arg.Tickers,
		arg.ReferenceLinks,
		arg.ReliabilityScore,
	)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Summary,
		&i.Sentiment,
		&i.Impact,
		&i.Tickers,
		&i.ReferenceLinks,
		&i.AnalyzedAt,
		&i.ReliabilityScore,
	)
	return i, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, link, content, source, published_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, link, content, source, published_at, created_at, status
`

type CreateArticleParams struct {
	Title       string    `json:"title"`
	Link        string    `json:"link"`
	Content     string    `json:"content"`
	Source      string    `json:"source"`
	PublishedAt time.Time `json:"published_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Link,
		arg.Content,
		arg.Source,
		arg.PublishedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Link,
		&i.Content,
		&i.Source,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const disableSource = `-- name: DisableSource :exec
UPDATE sources 
SET is_active = 0 
WHERE id = ?
`

func (q *Queries) DisableSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableSource, id)
	return err
}

const getActiveSources = `-- name: GetActiveSources :many
SELECT id, name, url, category, is_active, error_count, created_at FROM sources 
WHERE is_active = 1
`

func (q *Queries) GetActiveSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Category,
			&i.IsActive,
			&i.ErrorCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalysesByDate = `-- name: GetAnalysesByDate :many
SELECT 
    analyses.id, analyses.article_id, analyses.summary, analyses.sentiment, analyses.impact, analyses.tickers, analyses.reference_links, analyses.analyzed_at, analyses.reliability_score, 
    articles.id, articles.title, articles.link, articles.content, articles.source, articles.published_at, articles.created_at, articles.status
FROM analyses
JOIN articles ON analyses.article_id = articles.id
WHERE DATE(analyses.analyzed_at) = DATE(?)
ORDER BY analyses.analyzed_at DESC
`

type GetAnalysesByDateRow struct {
	Analysis Analysis `json:"analysis"`
	Article  Article  `json:"article"`
}

func (q *Queries) GetAnalysesByDate(ctx context.Context, date interface{}) ([]GetAnalysesByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getAnalysesByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalysesByDateRow
	for rows.Next() {
		var i GetAnalysesByDateRow
		if err := rows.Scan(
			&i.Analysis.ID,
			&i.Analysis.ArticleID,
			&i.Analysis.Summary,
			&i.Analysis.Sentiment,
			&i.Analysis.Impact,
			&i.Analysis.Tickers,
			&i.Analysis.ReferenceLinks,
			&i.Analysis.AnalyzedAt,
			&i.Analysis.ReliabilityScore,
			&i.Article.ID,
			&i.Article.Title,
			&i.Article.Link,
			&i.Article.Content,
			&i.Article.Source,
			&i.Article.PublishedAt,
			&i.Article.CreatedAt,
			&i.Article.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, link, content, source, published_at, created_at, status FROM articles WHERE id = ? LIMIT 1
`

func (q *Queries) GetArticleByID(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Link,
		&i.Content,
		&i.Source,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getNextPendingArticle = `-- name: GetNextPendingArticle :one
SELECT id, title, link, content, source, published_at, created_at, status FROM articles 
WHERE status = 'PENDING' 
ORDER BY published_at ASC 
LIMIT 1
`

func (q *Queries) GetNextPendingArticle(ctx context.Context) (Article, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingArticle)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Link,
		&i.Content,
		&i.Source,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getRecentAnalyses = `-- name: GetRecentAnalyses :many
SELECT 
    analyses.id, analyses.article_id, analyses.summary, analyses.sentiment, analyses.impact, analyses.tickers, analyses.reference_links, analyses.analyzed_at, analyses.reliability_score, 
    articles.id, articles.title, articles.link, articles.content, articles.source, articles.published_at, articles.created_at, articles.status
FROM analyses
JOIN articles ON analyses.article_id = articles.id
ORDER BY analyses.analyzed_at DESC
LIMIT ?
`

type GetRecentAnalysesRow struct {
	Analysis Analysis `json:"analysis"`
	Article  Article  `json:"article"`
}

func (q *Queries) GetRecentAnalyses(ctx context.Context, limit int64) ([]GetRecentAnalysesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentAnalyses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentAnalysesRow
	for rows.Next() {
		var i GetRecentAnalysesRow
		if err := rows.Scan(
			&i.Analysis.ID,
			&i.Analysis.ArticleID,
			&i.Analysis.Summary,
			&i.Analysis.Sentiment,
			&i.Analysis.Impact,
			&i.Analysis.Tickers,
			&i.Analysis.ReferenceLinks,
			&i.Analysis.AnalyzedAt,
			&i.Analysis.ReliabilityScore,
			&i.Article.ID,
			&i.Article.Title,
			&i.Article.Link,
			&i.Article.Content,
			&i.Article.Source,
			&i.Article.PublishedAt,
			&i.Article.CreatedAt,
			&i.Article.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementSourceError = `-- name: IncrementSourceError :exec
UPDATE sources 
SET error_count = error_count + 1 
WHERE id = ?
`

func (q *Queries) IncrementSourceError(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementSourceError, id)
	return err
}

const searchAnalyses = `-- name: SearchAnalyses :many
SELECT 
    analyses.id, analyses.article_id, analyses.summary, analyses.sentiment, analyses.impact, analyses.tickers, analyses.reference_links, analyses.analyzed_at, analyses.reliability_score, 
    articles.id, articles.title, articles.link, articles.content, articles.source, articles.published_at, articles.created_at, articles.status
FROM analyses
JOIN articles ON analyses.article_id = articles.id
WHERE articles.title LIKE '%' || ? || '%' 
   OR analyses.tickers LIKE '%' || ? || '%'
ORDER BY analyses.analyzed_at DESC
LIMIT 30
`

type SearchAnalysesParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
}

type SearchAnalysesRow struct {
	Analysis Analysis `json:"analysis"`
	Article  Article  `json:"article"`
}

func (q *Queries) SearchAnalyses(ctx context.Context, arg SearchAnalysesParams) ([]SearchAnalysesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAnalyses, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAnalysesRow
	for rows.Next() {
		var i SearchAnalysesRow
		if err := rows.Scan(
			&i.Analysis.ID,
			&i.Analysis.ArticleID,
			&i.Analysis.Summary,
			&i.Analysis.Sentiment,
			&i.Analysis.Impact,
			&i.Analysis.Tickers,
			&i.Analysis.ReferenceLinks,
			&i.Analysis.AnalyzedAt,
			&i.Analysis.ReliabilityScore,
			&i.Article.ID,
			&i.Article.Title,
			&i.Article.Link,
			&i.Article.Content,
			&i.Article.Source,
			&i.Article.PublishedAt,
			&i.Article.CreatedAt,
			&i.Article.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticleStatus = `-- name: UpdateArticleStatus :exec
UPDATE articles 
SET status = ? 
WHERE id = ?
`

type UpdateArticleStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateArticleStatus(ctx context.Context, arg UpdateArticleStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateArticleStatus, arg.Status, arg.ID)
	return err
}
