// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAnalysis = `-- name: CreateAnalysis :one
INSERT INTO analyses (article_id, summary, sentiment, impact, tickers, reference_links, reliability_score)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, article_id, summary, sentiment, impact, tickers, reference_links, analyzed_at, reliability_score
`

type CreateAnalysisParams struct {
	ArticleID        int64  `json:"article_id"`
	Summary          string `json:"summary"`
	Sentiment        string `json:"sentiment"`
	Impact           string `json:"impact"`
	Tickers          string `json:"tickers"`
	ReferenceLinks   string `json:"reference_links"`
	ReliabilityScore int64  `json:"reliability_score"`
}

func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error) {
	row := q.db.QueryRowContext(ctx, createAnalysis,
		arg.ArticleID,
		arg.Summary,
		arg.Sentiment,
		arg.Impact,
		arg.Tickers,
		arg.ReferenceLinks,
		arg.ReliabilityScore,
	)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Summary,
		&i.Sentiment,
		&i.Impact,
		&i.Tickers,
		&i.ReferenceLinks,
		&i.AnalyzedAt,
		&i.ReliabilityScore,
	)
	return i, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, link, content, source, published_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, link, content, source, published_at, created_at
`

type CreateArticleParams struct {
	Title       string    `json:"title"`
	Link        string    `json:"link"`
	Content     string    `json:"content"`
	Source      string    `json:"source"`
	PublishedAt time.Time `json:"published_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Link,
		arg.Content,
		arg.Source,
		arg.PublishedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Link,
		&i.Content,
		&i.Source,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentAnalyses = `-- name: GetRecentAnalyses :many
SELECT 
    analyses.id, analyses.article_id, analyses.summary, analyses.sentiment, analyses.impact, analyses.tickers, analyses.reference_links, analyses.analyzed_at, analyses.reliability_score, 
    articles.id, articles.title, articles.link, articles.content, articles.source, articles.published_at, articles.created_at
FROM analyses
JOIN articles ON analyses.article_id = articles.id
ORDER BY analyses.analyzed_at DESC
LIMIT ?
`

type GetRecentAnalysesRow struct {
	Analysis Analysis `json:"analysis"`
	Article  Article  `json:"article"`
}

func (q *Queries) GetRecentAnalyses(ctx context.Context, limit int64) ([]GetRecentAnalysesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentAnalyses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentAnalysesRow
	for rows.Next() {
		var i GetRecentAnalysesRow
		if err := rows.Scan(
			&i.Analysis.ID,
			&i.Analysis.ArticleID,
			&i.Analysis.Summary,
			&i.Analysis.Sentiment,
			&i.Analysis.Impact,
			&i.Analysis.Tickers,
			&i.Analysis.ReferenceLinks,
			&i.Analysis.AnalyzedAt,
			&i.Analysis.ReliabilityScore,
			&i.Article.ID,
			&i.Article.Title,
			&i.Article.Link,
			&i.Article.Content,
			&i.Article.Source,
			&i.Article.PublishedAt,
			&i.Article.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAnalyses = `-- name: SearchAnalyses :many
SELECT 
    analyses.id, analyses.article_id, analyses.summary, analyses.sentiment, analyses.impact, analyses.tickers, analyses.reference_links, analyses.analyzed_at, analyses.reliability_score, 
    articles.id, articles.title, articles.link, articles.content, articles.source, articles.published_at, articles.created_at
FROM analyses
JOIN articles ON analyses.article_id = articles.id
WHERE articles.title LIKE '%' || ? || '%' 
   OR analyses.tickers LIKE '%' || ? || '%'
ORDER BY analyses.analyzed_at DESC
LIMIT 30
`

type SearchAnalysesParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
}

type SearchAnalysesRow struct {
	Analysis Analysis `json:"analysis"`
	Article  Article  `json:"article"`
}

func (q *Queries) SearchAnalyses(ctx context.Context, arg SearchAnalysesParams) ([]SearchAnalysesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAnalyses, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAnalysesRow
	for rows.Next() {
		var i SearchAnalysesRow
		if err := rows.Scan(
			&i.Analysis.ID,
			&i.Analysis.ArticleID,
			&i.Analysis.Summary,
			&i.Analysis.Sentiment,
			&i.Analysis.Impact,
			&i.Analysis.Tickers,
			&i.Analysis.ReferenceLinks,
			&i.Analysis.AnalyzedAt,
			&i.Analysis.ReliabilityScore,
			&i.Article.ID,
			&i.Article.Title,
			&i.Article.Link,
			&i.Article.Content,
			&i.Article.Source,
			&i.Article.PublishedAt,
			&i.Article.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
